version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    networks:
      - net
    volumes:
      - volumes-1:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - 3306:3306

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-server
    environment:
      NODE_ENV: development
      DATABASE_URL: "mysql://root:pass@mysql-container:3306/mysql-container"
    networks:
      - net
    volumes:
      - .:/app
    ports:
      - 3030:3030
      - 5555:5555
    depends_on:
      - mysql

networks:
  net:
    driver: bridge
volumes:
  volumes-1:
    driver: local
